spring.application.name=demo
spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce_db
spring.datasource.username=root
spring.datasource.password=Jay@mysql27

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
app.admin.name=Store Admin
app.admin.email=admin@shop.com
app.admin.password=Admin@123
